### PR TITLE
fix(subscription): omit plan name when empty in create payload

### LINKED ISSUE #430: [BUG] Subscription is leaked when plan is the empty string
**Describe the bug**

This is a describe output for a `Subscription` resource:

```yaml
Name:         zzz-ojrfe7-cid-6khgip
Namespace:    
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  crossplane.io/external-create-failed: 2025-12-04T14:29:29Z
              crossplane.io/external-create-pending: 2025-12-04T14:29:29Z
              crossplane.io/external-create-succeeded: 2025-12-04T14:27:22Z
              crossplane.io/external-name: cloudciservice-635e3a0f-282a-489b-941c-8f6bd3a2f6f9/
              meta.helm.sh/release-name: zzz-ojrfe7-test-subsc-ne8ygq
              meta.helm.sh/release-namespace: default
API Version:  account.btp.sap.crossplane.io/v1alpha1
Kind:         Subscription
Metadata:
  Creation Timestamp:  2025-12-04T14:27:21Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        2
  Resource Version:  38037136
  UID:               02ebdbf9-5459-4ea2-abf8-1f0fa22f2c92
Spec:
  Cloud Management Ref:
    Name:                             zzz-iwzx6k-5j1jfh
  Cloud Management Secret:            zzz-iwzx6k-5j1jfh
  Cloud Management Secret Namespace:  default
  Deletion Policy:                    Delete
  For Provider:
    App Name:   cloudciservice-635e3a0f-282a-489b-941c-8f6bd3a2f6f9
    Plan Name:  
  Management Policies:
    *
  Provider Config Ref:
    Name:  btp-provider-config
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2025-12-04T14:27:22Z
    Observed Generation:   2
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2025-12-04T14:27:54Z
    Message:               create failed: API Error: Subaccount XXXXXXXXXXXXXXXXX is already subscribed to this app., Code 90002
    Observed Generation:   2
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                        Age                    From                                                Message
  ----     ------                        ----                   ----                                                -------
  Normal   CreatedExternalResource       2m33s                  managed/subscription.account.btp.sap.crossplane.io  Successfully requested creation of external resource
  Normal   PendingExternalResource       2m18s (x4 over 2m32s)  managed/subscription.account.btp.sap.crossplane.io  Waiting for external resource existence to be confirmed
  Warning  CannotCreateExternalResource  26s (x3 over 2m1s)     managed/subscription.account.btp.sap.crossplane.io  API Error: Subaccount XXXXXXXXXXXXXXXXX is already subscribed to this app., Code 90002
```

The requested resource actually got created successfully, but the provider does not "adopt" the newly created subscription. I assume it retries and ends up with a conflict. The created subscription is now a leaked external resource.

The reason is obviously, that `appPlan` is set to the empty string.

**Tested with Provider Version**
v1.4.0

**To Reproduce**

Create a subscription resource with an empty string as plan. For the subscription to be successful, a PaaS App is required which except the empty string as plan.

**Expected behavior**
The subscription ends up in ready and synced state. Or if this cannot be solved, it must end up in pending create state.

**Additional context**

Why use an empty String as `appPlan`?

The empty string is in fact a valid value in the [create subscription API](https://api.sap.com/api/APISaasManagerService/path/createSubscriptionAsync). It is also useful if you want to subscribe to an application which is not yet registered with xrs. In that situation, the app will be available for subscription in the same global account, but it will not have plans. To subscribe it, the plan value is omitted or set to the empty string.

### PR DESCRIPTION
**Pull request by lennardrother**
Fixes #430 

Passing `{ "planName": "" }` to the SAP SaaS Provisioning Service API when subscribing creates a new entitled application instead of subscribing to the existing one. This leaves the existing one with "state": "NOT_SUBSCRIBED".

Observe gets the existing one, tries to subscribe and receives a HTTP 409 Conflict because the subaccount is already subscribed to the application.

We avoid this by omitting `planName` when it's empty.

### CODE REVIEW

File: internal/clients/subscription/subscription.go [hunk 1]
```diff
@@ -174,10 +174,18 @@ func (s *SubscriptionTypeMapper) SyncStatus(get *SubscriptionGet, crStatus *v1al
 }
 
 func (s *SubscriptionTypeMapper) ConvertToCreatePayload(cr *v1alpha1.Subscription) SubscriptionPost {
+	// Passing { "planName": "" } to the SAP SaaS Provisioning Service API when subscribing creates a new entitled application instead of subscribing to the existing one.
+	// This leaves the existing one with "state": "NOT_SUBSCRIBED".
+	// Observe gets the existing one, tries to subscribe and receives a HTTP 409 Conflict because the subaccount is already subscribed to the application.
+	// We avoid this by omitting the planName when it's empty.
```
Comment (enrico-kaack-comp) [inline internal/clients/subscription/subscription.go:180]: great research and explanation, thank you!

**Review by enrico-kaack-comp — APPROVED** [review]
